apiVersion: apiextensions.crossplane.io/v1beta1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.aws.platform.absa.africa
  annotations:
    upbound.io/ui-schema: |-
      ---
      ppspspspspspspspsppspspspspspspspp
spec:
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  group: aws.platform.absa.africa
  names:
    kind: CompositePostgreSQLInstance
    plural: compositepostgresqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                  networkRef:
                    type: object
                    description: "A reference to the Network object that this postgres should be
                    connected to."
                    properties:
                      id:
                        type: string
                        description: ID of the Network object this ref points to.
                    required:
                    - id
                required:
                  - storageGB
                  - networkRef
            required:
              - parameters